# Generated by Django 3.0.2 on 2020-01-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('nationalId', models.CharField(max_length=100)),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
